### ISSUE TITLE
Error with SDK editor

### ISSUE THREAD

**Issue by 1bye** [stackblitz/sdk#23]
I've been using the embedProject from the SDK for a long time, but today I encountered the following errors with the same code that worked in previous months:

Console errors:
```bash
run?embed=1&theme=light&view=editor:8 Uncaught (in promise) 
Error: Could not find source file: 'stackblitz:/.etc/output.ts'.
    at g (mts5w-5f2f16260d5ca.js:7:1667344)
    at Object.getSyntacticDiagnostics (mts5w-5f2f16260d5ca.js:7:1674772)
    at e.getSyntacticDiagnostics (mts5w-5f2f16260d5ca.js:7:4872306)
    at e.<anonymous> (mts5w-5f2f16260d5ca.js:7:4913775)
    at r.fmr (workerMain.js:13:116573)
    at a._handleMessage (workerMain.js:13:65955)
    at Object.handleMessage (workerMain.js:13:65622)
    at f._handleMessage (workerMain.js:13:63696)
    at f.handleMessage (workerMain.js:13:63305)
    at a.onmessage (workerMain.js:13:65672)
run?embed=1&theme=light&view=editor:8 Uncaught (in promise) 
Error: Could not find source file: 'stackblitz:/.etc/run.ts'.
    at g (mts5w-5f2f16260d5ca.js:7:1667344)
    at Object.getSyntacticDiagnostics (mts5w-5f2f16260d5ca.js:7:1674772)
    at e.getSyntacticDiagnostics (mts5w-5f2f16260d5ca.js:7:4872306)
    at e.<anonymous> (mts5w-5f2f16260d5ca.js:7:4913775)
    at r.fmr (workerMain.js:13:116573)
    at a._handleMessage (workerMain.js:13:65955)
    at Object.handleMessage (workerMain.js:13:65622)
    at f._handleMessage (workerMain.js:13:63696)
    at f.handleMessage (workerMain.js:13:63305)
    at a.onmessage (workerMain.js:13:65672)
run?embed=1&theme=light&view=editor:8 Uncaught (in promise) 
Error: Could not find source file: 'stackblitz:/.etc/types.d.ts'.
    at g (mts5w-5f2f16260d5ca.js:7:1667344)
    at Object.getSyntacticDiagnostics (mts5w-5f2f16260d5ca.js:7:1674772)
    at e.getSyntacticDiagnostics (mts5w-5f2f16260d5ca.js:7:4872306)
    at e.<anonymous> (mts5w-5f2f16260d5ca.js:7:4913775)
    at r.fmr (workerMain.js:13:116573)
    at a._handleMessage (workerMain.js:13:65955)
    at Object.handleMessage (workerMain.js:13:65622)
    at f._handleMessage (workerMain.js:13:63696)
    at f.handleMessage (workerMain.js:13:63305)
    at a.onmessage (workerMain.js:13:65672)
run?embed=1&theme=light&view=editor:8 Uncaught (in promise) 
Error: Could not find source file: 'stackblitz:/.etc/globals.d.ts'.
    at g (mts5w-5f2f16260d5ca.js:7:1667344)
    at Object.getSyntacticDiagnostics (mts5w-5f2f16260d5ca.js:7:1674772)
    at e.getSyntacticDiagnostics (mts5w-5f2f16260d5ca.js:7:4872306)
    at e.<anonymous> (mts5w-5f2f16260d5ca.js:7:4913775)
    at r.fmr (workerMain.js:13:116573)
    at a._handleMessage (workerMain.js:13:65955)
    at Object.handleMessage (workerMain.js:13:65622)
    at f._handleMessage (workerMain.js:13:63696)
    at f.handleMessage (workerMain.js:13:63305)
    at a.onmessage (workerMain.js:13:65672)
run?embed=1&theme=light&view=editor:8 Uncaught (in promise) 
Error: Could not find source file: 'stackblitz:/.etc/output.ts'.
    at g (mts5w-5f2f16260d5ca.js:7:1667344)
    at Object.getSyntacticDiagnostics (mts5w-5f2f16260d5ca.js:7:1674772)
    at e.getSyntacticDiagnostics (mts5w-5f2f16260d5ca.js:7:4872306)
    at e.<anonymous> (mts5w-5f2f16260d5ca.js:7:4913775)
    at r.fmr (workerMain.js:13:116573)
    at a._handleMessage (workerMain.js:13:65955)
    at Object.handleMessage (workerMain.js:13:65622)
    at f._handleMessage (workerMain.js:13:63696)
    at f.handleMessage (workerMain.js:13:63305)
    at a.onmessage (workerMain.js:13:65672)
run?embed=1&theme=light&view=editor:8 Uncaught (in promise) 
Error: Could not find source file: 'stackblitz:/.etc/run.ts'.
    at g (mts5w-5f2f16260d5ca.js:7:1667344)
    at Object.getSyntacticDiagnostics (mts5w-5f2f16260d5ca.js:7:1674772)
    at e.getSyntacticDiagnostics (mts5w-5f2f16260d5ca.js:7:4872306)
    at e.<anonymous> (mts5w-5f2f16260d5ca.js:7:4913775)
    at r.fmr (workerMain.js:13:116573)
    at a._handleMessage (workerMain.js:13:65955)
    at Object.handleMessage (workerMain.js:13:65622)
    at f._handleMessage (workerMain.js:13:63696)
    at f.handleMessage (workerMain.js:13:63305)
    at a.onmessage (workerMain.js:13:65672)
```

Do you have any ideas on what might be causing this? Have there been any recent changes to the API?
If you need I can provide files which I using in embedProject
Thanks!

**Comment by abhishekjakhar** [comment]
I also get similar errors.
